<h2>Plus Learning Tuition in Rossendale - CEM 11+ Exam Preparation for Grammar School Entrance Exams </h2>
<h3><em>I'm now fully booked for regular tuition for 2019-2020. If you'd like to be added to a waiting list please email me. I can also add you to a list to take one-off cancellations when my regular students are unable to attend. </em></h3>
<h3><em>I also run mock tests in the summer holidays so email me if you'd like me to contact you in the summer term with details.</em></h3>
<h3><img src="http://www.pluslearningtuition.com/wp-content/uploads/2018/05/aaaaa-1-1-215x300.jpg" alt="working towards the 11+" width="215" height="300" /></h3>
<h3>Tuition Details</h3>
    <p><strong>My tuition sessions are for current year 5 children only</strong>, in groups of up to five children per session. Group sessions allow children to work both collaboratively and individually (depending on the material) and my students enjoy the camaraderie of small group sessions, with many past students making friends within their groups that they carry forward into high school. They've also found the skills developed and consolidated over the year invaluable for year 6 and SATs work. <strong>My pass rate for 2017-18 for children who studied with me from Autumn 2017 and took the BRGS entrance exam in September 2018 was 80%. </strong> I'm very proud of my students' successes, and enjoy seeing them grow in confidence over the year.

        <strong>We meet for an hour weekly</strong> (during term time and throughout the summer holidays) until the grammar school entrance exam which is held in September of Year 6. In that time, students study all the required aspects of English, Maths, Verbal Reasoning and Non-Verbal Reasoning. Material includes worksheets, tests and online quizzes and activities. I use resources from a variety of 11+ providers such as CEM (Durham University), Bond, CGP, NFER Nelson, and First Past the Post as well as material I've devised myself. This variety ensures your child will be more than ready to tackle 11+ style questions in whatever format and style they are presented in the test.

    <strong>Tuition fees are paid monthly and are due in advance</strong> by the 1st lesson of each month, or half-termly if you prefer. Fees include all materials, online quizzes and activities, workbooks used for homework and tests. <strong>Fees are not refundable for missed sessions</strong>, except for 2x weeks holiday per year. <strong>If your child is unable to attend a scheduled session</strong> (due to holidays, illness or a prior engagement) I will try to accommodate your child in an alternative session, but this is not always possible - in which case I'll ensure your child has access to all the material they missed. You don't pay for sessions I cancel, or for weeks that we don't meet (such as half-term, Christmas holidays and Easter holidays). We do meet throughout the summer holidays but if you have holidays booked during that time (up to two weeks) there's no fee to pay for those weeks. I also do extra sessions during the summer holidays should you feel your child would benefit from them. For term dates see below. <strong>Please contact me</strong> by emailing <a href="mailto:pluslearningtuition@gmail.com" target="_top">pluslearningtuition@gmail.com</a> or register your interest by 'booking' your chosen time below. Booking online is the easiest way to see real-time availability for dates and times. Just sign up for tuition on your chosen session leaving your details and I'll contact you to confirm a reservation for that day and time. Your child's place will be ongoing throughout the year - there's no need to book your child onto the lesson every week. Click below to book.</p>
<div>[10to8booking organisation_id="24974017-245a-41c2-8701-ba90fc232a7e"]</div>
<h3><img src="http://www.pluslearningtuition.com/wp-content/uploads/2018/05/a-test3-1.jpg" alt="multiple choice answer sheet for the 11+" width="275" height="183" /></h3>
<h3>2019 (new intake) TUITION DATES - Autumn Term - WEDNESDAY GROUPS</h3>
<p><strong>September lessons</strong> will be on the following dates: 18th and 25th (two weeks so pay weekly) <strong>October lessons</strong> will be on the following dates: 2nd, 9th, 16th and 30th (4 weeks' fees due 1st of the month) <strong>November lessons</strong> will be on the following dates: 6th, 13th, 20th and 27th (4 weeks' fees due 1st of the month) <strong>December lessons</strong> will be on the following dates: 4th, 11th and 18th (3 weeks' fees due on 1st of the month) Half term holiday - week of Wednesday 23rd October 2019 Christmas holiday - weeks of 25th December 2019 and 1st January 2020</p>
<h3>2019 (new intake) TUITION DATES - Autumn Term - THURSDAY GROUPS</h3>
<p><strong>September lessons</strong> will be on the following dates: 19th and 26th (two weeks so pay weekly) <strong>October lessons</strong> will be on the following dates: 3rd, 10th, 17th and 31st (4 weeks' fees due on 1st of the month) <strong>November lessons</strong> will be on the following dates: 7th, 14th, 21st and 28th (4 weeks' fees due on 1st of the month) <strong>December lessons</strong> will be on the following dates: 5th, 12th and 19th (3 weeks' fees due on 1st of the month) Half term holiday - week of Thursday 24th October 2019 Christmas holiday - weeks of 26th December 2019 and 2nd January 2020</p>
<h1>Tuition Location</h1>
<p>Rising Bridge Rd, Haslingden, BB4 5BL. <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2360.993078809271!2d-2.329896217412823!3d53.71838567972567!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487b98795aad705f%3A0xe50bba41246798cb!2sPlus+Learning+Tuition%2C+(11%2B+prep)+Rossendale!5e0!3m2!1sen!2suk!4v1497520791991" width="100%" height="250" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>